name: 'Deploy'

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sentry Deploys
        uses: tctree333/SciOlyID-Actions/sentry@master
        with:
          sentry auth: ${{ secrets.SENTRY_TOKEN }}
          sentry org: 'sciolyid'
          sentry project 1: treebo

      - name: Deploy to Dokku
        uses: tctree333/SciOlyID-Actions/deploy-dokku@master
        with:
          dokku app name: treebo
          dokku host: ${{ secrets.DOKKU_HOST }}
          ssh private key: ${{ secrets.PRIVATE_KEY }}
          deploy branch: main
